---
title: "Dissertation Info"
description: |
  Coming Soon!
output:
  distill::distill_article:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(emo)
```


### Important Dates

Ethics: week 8

Analysis plan: Dec

First draft & feedback: TBD

Dissertation standard deadline: May 2022


### A Very Rough Timeline

Oct: Read up on topic area, decide on research question, hypotheses and methodology  

Nov: Prepare materials, refine method and submit ethics  

Dec: Do analysis plan, start data collection and draft method section

Jan: Continue data collection, start on analysis and draft intro

Feb: Draft results and discussion

March: Feedback on first draft

April: Final edits 

May: Submit!! `r emo::ji("partying_face")`


### Analysis Plan


An analysis plan is a very useful tool that helps you to ensure that your method is appropriate to test your hypotheses. By thinking about your analysis in advance, you can better anticipate any problems with your design that could negatively impact the quality of your data. Writing up the method section of your dissertation is also much easier when you have already completed an analysis plan that you can refer back to. You should complete the [Dissertation Analysis Plan](./docs/DAP.docx) prior to collecting any data.  




### Working with Secondary Data

Coming Soon! 

<br>
